apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: civo-ai-agent
  namespace: default
spec:
  image: ghcr.io/RanaAarav/CIVO-Spin-AI-Agent
  replicas: 3
  executor: containerd-shim-spin-v2
